name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      # https://docs.github.com/en/actions/reference/encrypted-secrets
      #env:
      #  NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}
    - name: Setup .NET
      # Authenticates packages to push to GPR
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://www.nuget.org/api/v2/package
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release -o ./artifacts
#    - name: Publish the package to Nuget
#      run: dotnet nuget push ./artifacts/*.nupkg -k "$NUGET_AUTH_TOKEN"
#      if: github.event == 'push'

